# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.2
language: swift
# cache: cocoapods
podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- swift package generate-xcodeproj
- xcodebuild -workspace Example/SYGalleryPicker.xcworkspace -scheme SYGalleryPicker-Example -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=13.0' -enableCodeCoverage YES build test
- pod lib lint --quick
after_success:
- bash <(curl -s https://codecov.io/bash)
